name: Analysis

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Test puppeteer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run test
        uses: tj-actions/puppeteer@v5
        id: puppeteer
        with:
          files: test.js
